import { readSessionEvents } from "./events.mjs";
import { readSessionTokens } from "./tokens.mjs";
import {
  assertDeepCleanupSupported,
  diagnoseStorageCompatibility,
  deleteSessionDeletionBackup,
  executeSessionDeletion,
  fingerprintSessionDeletion,
  filterAndSortSessions,
  formatSessionForJson,
  getSessionOverview,
  getSessionRecord,
  invalidateSessionCache,
  listSessionDeletionBackups,
  listSessions,
  loadDeletionStore,
  loadSessionStore,
  planSessionDeletion,
  preflightSessionDeletion,
  restoreSessionDeletionBackup,
  verifySessionDeletion,
} from "./store.mjs";

export const codexProvider = Object.freeze({
  id: "codex",
  displayName: "Codex",
  assertDeepCleanupSupported,
  diagnoseStorageCompatibility,
  deleteSessionDeletionBackup,
  executeSessionDeletion,
  fingerprintSessionDeletion,
  filterAndSortSessions,
  formatSessionForJson,
  getSessionOverview,
  getSessionRecord,
  invalidateSessionCache,
  listSessionDeletionBackups,
  listSessions,
  loadDeletionStore,
  loadSessionStore,
  planSessionDeletion,
  preflightSessionDeletion,
  readSessionEvents,
  readSessionTokens,
  restoreSessionDeletionBackup,
  verifySessionDeletion,
});
