import {
  assertDeepCleanupSupported,
  diagnoseStorageCompatibility,
  executeSessionDeletion,
  fingerprintSessionDeletion,
  filterAndSortSessions,
  formatSessionForJson,
  getSessionRecord,
  listSessions,
  loadDeletionStore,
  loadSessionStore,
  planSessionDeletion,
  preflightSessionDeletion,
  restoreSessionDeletionBackup,
  verifySessionDeletion,
} from "./store.mjs";

export const codexProvider = Object.freeze({
  id: "codex",
  displayName: "Codex",
  assertDeepCleanupSupported,
  diagnoseStorageCompatibility,
  executeSessionDeletion,
  fingerprintSessionDeletion,
  filterAndSortSessions,
  formatSessionForJson,
  getSessionRecord,
  listSessions,
  loadDeletionStore,
  loadSessionStore,
  planSessionDeletion,
  preflightSessionDeletion,
  restoreSessionDeletionBackup,
  verifySessionDeletion,
});
